#!/bin/bash
set -euo pipefail

case ${OMPI_COMM_WORLD_LOCAL_RANK:-0} in
  0) export CUDA_VISIBLE_DEVICES=0,1; STOLK_NUMA_NODE=0 ;;
  1) export CUDA_VISIBLE_DEVICES=2,3; STOLK_NUMA_NODE=2 ;;
  *) echo "2r2g wrapper requires exactly two local MPI ranks" >&2; exit 8 ;;
esac

export UCX_MEMTYPE_CACHE=${UCX_MEMTYPE_CACHE:-n}
export UCX_NET_DEVICES=${UCX_NET_DEVICES:-all}
export UCX_MAX_RNDV_RAILS=${UCX_MAX_RNDV_RAILS:-4}
export STOLK_MPI_ASYNC_RANK_HALO=${STOLK_MPI_ASYNC_RANK_HALO:-1}
export STOLK_MPI_CUDA_AWARE_HALO=${STOLK_MPI_CUDA_AWARE_HALO:-0}
export STOLK_MPI_ASYNC_DEVICE_HALO=${STOLK_MPI_ASYNC_DEVICE_HALO:-1}
export STOLK_MPI_DEFER_HOST_STAGED_SEND=${STOLK_MPI_DEFER_HOST_STAGED_SEND:-0}
export STOLK_MPI_HOST_PROGRESS_THREAD=${STOLK_MPI_HOST_PROGRESS_THREAD:-1}

exec numactl --cpunodebind="${STOLK_NUMA_NODE}" \
  --membind="${STOLK_NUMA_NODE}" "$@"
